### Health Check

GET http://localhost:5000/api/health

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "akshat@example.com",
    "password": "password123"
}

###

POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "name": "Akshat",
    "email": "akshat@example.com",
    "password": "password123"
}

###

GET http://localhost:5000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ2ZDkxODBlLWYxNmItNDBhNy1hNDczLTE3NmZmNWIxZjRkYSIsImlhdCI6MTc4MjgwMTU2NCwiZXhwIjoxNzgzNDA2MzY0fQ.066E7e2nOIGNve3CboYdFzazDDo_VWjsVpy53EttVe0